CREATE USER IF NOT EXISTS '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASS';
CREATE DATABASE IF NOT EXISTS $DB_NAME;

GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$DB_HOST';
FLUSH PRIVILEGES;

SELECT user, host FROM mysql.user WHERE user = '$DB_USER';
SHOW GRANTS FOR '$DB_USER'@'$DB_HOST';

